main: rubrub07.SimpleNBTSell.SimpleNBTSell
version: 0.0.1
author: rubrub07
depend: [NBTAPI, Vault,PlaceholderAPI]
softdepend: [MMOItems]
api-version: 1.16
name: SimpleNBTSell
commands:
      sns:
         description: comando principal